version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - "mongo_db:/data/db"
    ports:
      - "27017:27017"

volumes:
  mongo_db:

